version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "enyu-auto"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "enyu-auto"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "us-east-1"
