AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Enyu Auto Lambda Function

Globals:
  Function:
    Timeout: 300
    MemorySize: 512

Resources:
  EnyuAutoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: dist/index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          NODE_ENV: production

Outputs:
  EnyuAutoFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt EnyuAutoFunction.Arn
